{
    'name': 'Libre',
    'version': '13.0.1.0.0',
    'category': 'App',
    'summary': 'Libre',
    'author': 'Nerijus Girskis',
    'maintainer': 'NG solution',
    'website': 'https://odoo.ngsolution.eu',
    'live_test_url': 'https://odoo.ngsolution.eu',
    'depends': [
        'base',
        'hr',
        'mail',
    ],
    'demo': [],
    'data': [        
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/data.xml',
        'views/menu.xml',
        'views/document.xml',
        'reports/report.xml',
        'reports/document_report.xml',
        'wizards/document_wizard.xml',
    ],
    'images': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
